name: PvpiSwap
version: ${project.version}
main: fr.isyde.Main
api-version: 1.16
authors: [ iSyde ]
description: Plugin Pvp
commands:
  addspawn:
    description: Ajoute un spawn pour le PvPiSwap
  addchest:
    description: Ajoute un chest pour le PvPiSwap
